/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedSimuladorRouteImport } from './routes/_authenticated/simulador'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedLucroPlataformaRouteImport } from './routes/_authenticated/lucro-plataforma'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedImportacoesRouteImport } from './routes/_authenticated/importacoes'
import { Route as AuthenticatedHistoricoPrecosRouteImport } from './routes/_authenticated/historico-precos'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedEvolucaoRouteImport } from './routes/_authenticated/evolucao'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComparativosRouteImport } from './routes/_authenticated/comparativos'
import { Route as AuthenticatedCmvRouteImport } from './routes/_authenticated/cmv'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCalculadoraPrecoRouteImport } from './routes/_authenticated/calculadora-preco'
import { Route as AuthenticatedAssistenteIaRouteImport } from './routes/_authenticated/assistente-ia'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as ApiPublicWhatsappTalktomeRouteImport } from './routes/api/public/whatsapp/talktome'
import { Route as ApiPublicWhatsappGeminiRouteImport } from './routes/api/public/whatsapp/gemini'
import { Route as ApiPublicIntegrationsSyncRouteImport } from './routes/api/public/integrations/sync'
import { Route as ApiPublicIntegrationsProviderWebhookRouteImport } from './routes/api/public/integrations/$provider/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSimuladorRoute = AuthenticatedSimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLucroPlataformaRoute =
  AuthenticatedLucroPlataformaRouteImport.update({
    id: '/lucro-plataforma',
    path: '/lucro-plataforma',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportacoesRoute =
  AuthenticatedImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoricoPrecosRoute =
  AuthenticatedHistoricoPrecosRouteImport.update({
    id: '/historico-precos',
    path: '/historico-precos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEvolucaoRoute = AuthenticatedEvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComparativosRoute =
  AuthenticatedComparativosRouteImport.update({
    id: '/comparativos',
    path: '/comparativos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCmvRoute = AuthenticatedCmvRouteImport.update({
  id: '/cmv',
  path: '/cmv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculadoraPrecoRoute =
  AuthenticatedCalculadoraPrecoRouteImport.update({
    id: '/calculadora-preco',
    path: '/calculadora-preco',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssistenteIaRoute =
  AuthenticatedAssistenteIaRouteImport.update({
    id: '/assistente-ia',
    path: '/assistente-ia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappTalktomeRoute =
  ApiPublicWhatsappTalktomeRouteImport.update({
    id: '/api/public/whatsapp/talktome',
    path: '/api/public/whatsapp/talktome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappGeminiRoute = ApiPublicWhatsappGeminiRouteImport.update({
  id: '/api/public/whatsapp/gemini',
  path: '/api/public/whatsapp/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsSyncRoute =
  ApiPublicIntegrationsSyncRouteImport.update({
    id: '/api/public/integrations/sync',
    path: '/api/public/integrations/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsProviderWebhookRoute =
  ApiPublicIntegrationsProviderWebhookRouteImport.update({
    id: '/api/public/integrations/$provider/webhook',
    path: '/api/public/integrations/$provider/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/calculadora-preco': typeof AuthenticatedCalculadoraPrecoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/cmv': typeof AuthenticatedCmvRoute
  '/comparativos': typeof AuthenticatedComparativosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/historico-precos': typeof AuthenticatedHistoricoPrecosRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/lucro-plataforma': typeof AuthenticatedLucroPlataformaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/calculadora-preco': typeof AuthenticatedCalculadoraPrecoRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/cmv': typeof AuthenticatedCmvRoute
  '/comparativos': typeof AuthenticatedComparativosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao': typeof AuthenticatedEvolucaoRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/historico-precos': typeof AuthenticatedHistoricoPrecosRoute
  '/importacoes': typeof AuthenticatedImportacoesRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/lucro-plataforma': typeof AuthenticatedLucroPlataformaRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/simulador': typeof AuthenticatedSimuladorRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/assistente-ia': typeof AuthenticatedAssistenteIaRoute
  '/_authenticated/calculadora-preco': typeof AuthenticatedCalculadoraPrecoRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/cmv': typeof AuthenticatedCmvRoute
  '/_authenticated/comparativos': typeof AuthenticatedComparativosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evolucao': typeof AuthenticatedEvolucaoRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/historico-precos': typeof AuthenticatedHistoricoPrecosRoute
  '/_authenticated/importacoes': typeof AuthenticatedImportacoesRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/lucro-plataforma': typeof AuthenticatedLucroPlataformaRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/simulador': typeof AuthenticatedSimuladorRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/assistente-ia'
    | '/calculadora-preco'
    | '/categorias'
    | '/cmv'
    | '/comparativos'
    | '/configuracoes'
    | '/dashboard'
    | '/evolucao'
    | '/fornecedores'
    | '/historico-precos'
    | '/importacoes'
    | '/integracoes'
    | '/lucro-plataforma'
    | '/metas'
    | '/movimentacoes'
    | '/planos'
    | '/relatorios'
    | '/simulador'
    | '/suporte'
    | '/admin/usuarios'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/alertas'
    | '/assistente-ia'
    | '/calculadora-preco'
    | '/categorias'
    | '/cmv'
    | '/comparativos'
    | '/configuracoes'
    | '/dashboard'
    | '/evolucao'
    | '/fornecedores'
    | '/historico-precos'
    | '/importacoes'
    | '/integracoes'
    | '/lucro-plataforma'
    | '/metas'
    | '/movimentacoes'
    | '/planos'
    | '/relatorios'
    | '/simulador'
    | '/suporte'
    | '/admin/usuarios'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/alertas'
    | '/_authenticated/assistente-ia'
    | '/_authenticated/calculadora-preco'
    | '/_authenticated/categorias'
    | '/_authenticated/cmv'
    | '/_authenticated/comparativos'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/evolucao'
    | '/_authenticated/fornecedores'
    | '/_authenticated/historico-precos'
    | '/_authenticated/importacoes'
    | '/_authenticated/integracoes'
    | '/_authenticated/lucro-plataforma'
    | '/_authenticated/metas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/planos'
    | '/_authenticated/relatorios'
    | '/_authenticated/simulador'
    | '/_authenticated/suporte'
    | '/_authenticated/admin/usuarios'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicIntegrationsSyncRoute: typeof ApiPublicIntegrationsSyncRoute
  ApiPublicWhatsappGeminiRoute: typeof ApiPublicWhatsappGeminiRoute
  ApiPublicWhatsappTalktomeRoute: typeof ApiPublicWhatsappTalktomeRoute
  ApiPublicIntegrationsProviderWebhookRoute: typeof ApiPublicIntegrationsProviderWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulador': {
      id: '/_authenticated/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof AuthenticatedSimuladorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lucro-plataforma': {
      id: '/_authenticated/lucro-plataforma'
      path: '/lucro-plataforma'
      fullPath: '/lucro-plataforma'
      preLoaderRoute: typeof AuthenticatedLucroPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importacoes': {
      id: '/_authenticated/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof AuthenticatedImportacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico-precos': {
      id: '/_authenticated/historico-precos'
      path: '/historico-precos'
      fullPath: '/historico-precos'
      preLoaderRoute: typeof AuthenticatedHistoricoPrecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evolucao': {
      id: '/_authenticated/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof AuthenticatedEvolucaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comparativos': {
      id: '/_authenticated/comparativos'
      path: '/comparativos'
      fullPath: '/comparativos'
      preLoaderRoute: typeof AuthenticatedComparativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cmv': {
      id: '/_authenticated/cmv'
      path: '/cmv'
      fullPath: '/cmv'
      preLoaderRoute: typeof AuthenticatedCmvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora-preco': {
      id: '/_authenticated/calculadora-preco'
      path: '/calculadora-preco'
      fullPath: '/calculadora-preco'
      preLoaderRoute: typeof AuthenticatedCalculadoraPrecoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente-ia': {
      id: '/_authenticated/assistente-ia'
      path: '/assistente-ia'
      fullPath: '/assistente-ia'
      preLoaderRoute: typeof AuthenticatedAssistenteIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp/talktome': {
      id: '/api/public/whatsapp/talktome'
      path: '/api/public/whatsapp/talktome'
      fullPath: '/api/public/whatsapp/talktome'
      preLoaderRoute: typeof ApiPublicWhatsappTalktomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/gemini': {
      id: '/api/public/whatsapp/gemini'
      path: '/api/public/whatsapp/gemini'
      fullPath: '/api/public/whatsapp/gemini'
      preLoaderRoute: typeof ApiPublicWhatsappGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/sync': {
      id: '/api/public/integrations/sync'
      path: '/api/public/integrations/sync'
      fullPath: '/api/public/integrations/sync'
      preLoaderRoute: typeof ApiPublicIntegrationsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/$provider/webhook': {
      id: '/api/public/integrations/$provider/webhook'
      path: '/api/public/integrations/$provider/webhook'
      fullPath: '/api/public/integrations/$provider/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsProviderWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAssistenteIaRoute: typeof AuthenticatedAssistenteIaRoute
  AuthenticatedCalculadoraPrecoRoute: typeof AuthenticatedCalculadoraPrecoRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCmvRoute: typeof AuthenticatedCmvRoute
  AuthenticatedComparativosRoute: typeof AuthenticatedComparativosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvolucaoRoute: typeof AuthenticatedEvolucaoRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedHistoricoPrecosRoute: typeof AuthenticatedHistoricoPrecosRoute
  AuthenticatedImportacoesRoute: typeof AuthenticatedImportacoesRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedLucroPlataformaRoute: typeof AuthenticatedLucroPlataformaRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSimuladorRoute: typeof AuthenticatedSimuladorRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAssistenteIaRoute: AuthenticatedAssistenteIaRoute,
  AuthenticatedCalculadoraPrecoRoute: AuthenticatedCalculadoraPrecoRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCmvRoute: AuthenticatedCmvRoute,
  AuthenticatedComparativosRoute: AuthenticatedComparativosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvolucaoRoute: AuthenticatedEvolucaoRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedHistoricoPrecosRoute: AuthenticatedHistoricoPrecosRoute,
  AuthenticatedImportacoesRoute: AuthenticatedImportacoesRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedLucroPlataformaRoute: AuthenticatedLucroPlataformaRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSimuladorRoute: AuthenticatedSimuladorRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicIntegrationsSyncRoute: ApiPublicIntegrationsSyncRoute,
  ApiPublicWhatsappGeminiRoute: ApiPublicWhatsappGeminiRoute,
  ApiPublicWhatsappTalktomeRoute: ApiPublicWhatsappTalktomeRoute,
  ApiPublicIntegrationsProviderWebhookRoute:
    ApiPublicIntegrationsProviderWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
