/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcessoRouteImport } from './routes/acesso'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSuporteRouteImport } from './routes/_authenticated/suporte'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin.usuarios'
import { Route as ApiPublicWhatsappTalktomeRouteImport } from './routes/api/public/whatsapp/talktome'
import { Route as ApiPublicWhatsappGeminiRouteImport } from './routes/api/public/whatsapp/gemini'
import { Route as ApiPublicIntegrationsSyncRouteImport } from './routes/api/public/integrations/sync'
import { Route as ApiPublicIntegrationsProviderWebhookRouteImport } from './routes/api/public/integrations/$provider/webhook'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoRoute = AcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSuporteRoute = AuthenticatedSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWhatsappTalktomeRoute =
  ApiPublicWhatsappTalktomeRouteImport.update({
    id: '/api/public/whatsapp/talktome',
    path: '/api/public/whatsapp/talktome',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappGeminiRoute = ApiPublicWhatsappGeminiRouteImport.update({
  id: '/api/public/whatsapp/gemini',
  path: '/api/public/whatsapp/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIntegrationsSyncRoute =
  ApiPublicIntegrationsSyncRouteImport.update({
    id: '/api/public/integrations/sync',
    path: '/api/public/integrations/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsProviderWebhookRoute =
  ApiPublicIntegrationsProviderWebhookRouteImport.update({
    id: '/api/public/integrations/$provider/webhook',
    path: '/api/public/integrations/$provider/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/suporte': typeof AuthenticatedSuporteRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso': typeof AcessoRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/suporte': typeof AuthenticatedSuporteRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/integrations/sync': typeof ApiPublicIntegrationsSyncRoute
  '/api/public/whatsapp/gemini': typeof ApiPublicWhatsappGeminiRoute
  '/api/public/whatsapp/talktome': typeof ApiPublicWhatsappTalktomeRoute
  '/api/public/integrations/$provider/webhook': typeof ApiPublicIntegrationsProviderWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso'
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/movimentacoes'
    | '/suporte'
    | '/admin/usuarios'
    | '/admin/'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso'
    | '/auth'
    | '/reset-password'
    | '/categorias'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/movimentacoes'
    | '/suporte'
    | '/admin/usuarios'
    | '/admin'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/categorias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/suporte'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/'
    | '/api/public/integrations/sync'
    | '/api/public/whatsapp/gemini'
    | '/api/public/whatsapp/talktome'
    | '/api/public/integrations/$provider/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoRoute: typeof AcessoRoute
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicIntegrationsSyncRoute: typeof ApiPublicIntegrationsSyncRoute
  ApiPublicWhatsappGeminiRoute: typeof ApiPublicWhatsappGeminiRoute
  ApiPublicWhatsappTalktomeRoute: typeof ApiPublicWhatsappTalktomeRoute
  ApiPublicIntegrationsProviderWebhookRoute: typeof ApiPublicIntegrationsProviderWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso': {
      id: '/acesso'
      path: '/acesso'
      fullPath: '/acesso'
      preLoaderRoute: typeof AcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/suporte': {
      id: '/_authenticated/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AuthenticatedSuporteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/whatsapp/talktome': {
      id: '/api/public/whatsapp/talktome'
      path: '/api/public/whatsapp/talktome'
      fullPath: '/api/public/whatsapp/talktome'
      preLoaderRoute: typeof ApiPublicWhatsappTalktomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/gemini': {
      id: '/api/public/whatsapp/gemini'
      path: '/api/public/whatsapp/gemini'
      fullPath: '/api/public/whatsapp/gemini'
      preLoaderRoute: typeof ApiPublicWhatsappGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/sync': {
      id: '/api/public/integrations/sync'
      path: '/api/public/integrations/sync'
      fullPath: '/api/public/integrations/sync'
      preLoaderRoute: typeof ApiPublicIntegrationsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/$provider/webhook': {
      id: '/api/public/integrations/$provider/webhook'
      path: '/api/public/integrations/$provider/webhook'
      fullPath: '/api/public/integrations/$provider/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsProviderWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedSuporteRoute: typeof AuthenticatedSuporteRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedSuporteRoute: AuthenticatedSuporteRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoRoute: AcessoRoute,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicIntegrationsSyncRoute: ApiPublicIntegrationsSyncRoute,
  ApiPublicWhatsappGeminiRoute: ApiPublicWhatsappGeminiRoute,
  ApiPublicWhatsappTalktomeRoute: ApiPublicWhatsappTalktomeRoute,
  ApiPublicIntegrationsProviderWebhookRoute:
    ApiPublicIntegrationsProviderWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
